---
    mysql_root_username: root
    mysql_root_password: root
    mysql_user: mysql
    mysql_port: 3306
    mysql_datadir: /var/lib/mysql
    mysql_bind: 127.0.0.1
    mysql_pkg: mysql-server
    mysql_pid: /var/run/mysqld/mysqld.pid
    mysql_socket: /var/run/mysqld/mysqld.sock
    mysql_cnfpath: /etc/my.cnf
    mysql_service: mysql-community-server
    passwd: root
    mysqlPackage: mysql-community-server.x86_64