---
# filename: roles/mysql/tasks/configure.yml

  - name: Copy file configuration 
    template: 
      src: templates/my.cnf.j2
      dest: /etc/my.cnf
      force: yes
      mode: 0644 

  - name: copy script file
    template:
      src: files/script.sh
      dest: /tmp/script.sh
      mode: 0644


  - name: Set the mysql root password 
    shell: sh /tmp/script.sh 
    environment:
      PASSMYSQL: '{{mysql_root_password}}'
    register: passmysql

  - debug: 
      var: passmysql.stdout

  - name: Create my datatable
    mysql_db:
      login_user: "{{mysql_root_username}}"
      login_password: '{{mysql_root_password}}'
      name: '{{database}}'
      encoding: utf8
      collation: utf8_bin

  - name: Create MY_DBA user in MySQL and grant privileges
    mysql_user:
      login_user: "{{mysql_root_username}}"
      login_password: '{{mysql_root_password}}'
      user: "{{dbuser}}"  
      password: "{{dbpasswd}}"
      host: "{{item}}"
      priv: '{{database}}.*:ALL'
    with_items:
            - "127.0.0.1"
            - "192.168.60.6"
            - "192.168.60.7"