---
# filename: roles/mysql/tasks/configure.yml
  - name: copy script file
    template:
      src: files/script.sh
      dest: /tmp/script.sh
      mode: 0644


  - name: Set the mysql root password 
    shell: sh /tmp/script.sh 
    environment:
      PASSMYSQL: '{{passwd}}'
    register: passmysql

  - debug: 
      var: passmysql.stdout

  - name: Create my datatable
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: MY_DATATABLE
      encoding: utf8
      collation: utf8_bin

  - name: Create MY_DBA user in MySQL and grant privileges
    mysql_user:
      login_user: root
      login_password: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      user: rootDb123  
      password: rootPasswd123@.++++-
      host: "{{item}}"
      priv: 'MY_DATATABLE.*:ALL'
    with_items:
            - "127.0.0.1"
            - "192.168.60.6"
            - "192.168.60.7"