---
# filename: roles/mysql/tasks/install_RedHat.yml

# - name: Download mysql57-community-release-el7-11.noarch.rpm
#   get_url:
#     url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
#     dest: /tmp/mysql57-community-release-el7-11.noarch.rpm
#     mode: '0644'

  - name: Get YUM repository for Mysql
    get_url:
      url: http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
      dest: /tmp/mysql57-community-release-el7-11.noarch.rpm
    become: yes

  - name: "Install Local RPMs"
    shell: yum localinstall -y /tmp/mysql57-community-release-el7-11.noarch.rpm
    become: yes

  - name: Install the MySQL repo.
    yum:
      name: "{{ mysqlPackage }}"
      state: present


  - name: Launch MySQL service
    service:
      name: mysqld
      state: started
      enabled: yes


  - name: Install required python MySQLdb lib to create databases and users
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - gcc-c++
      - MySQL-python