---
# filename: roles/mysql/tasks/install_RedHat.yml

# - name: Download mysql57-community-release-el7-11.noarch.rpm
#   get_url:
#     url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
#     dest: /tmp/mysql57-community-release-el7-11.noarch.rpm
#     mode: '0644'

- name: install mysql server
  yum: 
    name: mariadb-server mariadb
    state: present
