---
# handlers file for mysql
    - name: restart mysqld
      service:
        name: mysqld
        state: restarted  
        
    - name: start mysqld
      service:
        name: mysqld
        state: started