---
# essential tasks. should run on all nodes
    - name: creat yhe devops group
      group:
        name: devops
        state: present
    - name: create devops user with admin privileges
      user:
        name: devops
        comment: "Devops User"
        uid: 2001
        group: devops
    - name: update
      yum:
        name: "*"
        state: present
    
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
        
    - name: install htop package
      yum:
        name: htop
        state: present